### ISSUE TITLE
node.js: "syllable unicorn" produces 5 instead of 6 inside shell

### ISSUE THREAD

**Issue by jimmyhsu** [wooorm/syllable#1]
The following in node.js on 10.36 and 12.2:
`console.log("syllable unicorn", syllable("syllable unicorn"));`
produces 5 instead of the correct 6 like in the shell directly.

My current solution is to just split the string by spaces and add up the values to find the total syllables in the line.

My experience with NLP is limited, so at the moment I'm not quite sure what went wrong where, but I'll dig through and see what I can find.

Thanks for the npm module! It's been the best I've found so far.

**Comment by wooorm** [comment]
Right, that’s true. The idea behind it was that the definition of a “word” is pretty vague, and therefore out of syllable’s scope but left to other implementors. As the CLI is a simple implementation of syllable, i added a space-splitter there though.

Anyway, check out parse-english, or parse-latin, for word tokenisation; and retext-syllable for an example implementation with these tools.

But, to be honest, just splitting on non-alphabetical characters will probably work well enough :)
